project:
  type: book
  render:
    - "*.qmd"
    - "!slides/" # do not render slides folder
  output-dir: _rendered
    
book:
  title: "Open Source Technology in Clinical Data Analysis"
  #subtitle: "Data Visualisation & Open Source Technology Working Group"
  edition: "DRAFT"
  author: "PHUSE"
  abstract: "A significant amount of time and energy has been invested in recent years exploring the desirability (do we want it?), feasibility (can we do it?), and viability (is it worth it?) of integrating open source solutions into our clinical data pipelines which transform source data into clinical study reports and submission data packages. When this manuscsript is complete, we hope to put to rest some of the burning questions that we believe we now know the answers to. This will allow industry, and all the passionate people in it, to look ahead and start tackling the next horizon of challenges related to using open source solutions for clinical data pipelines. We hope you will contribute your expertise to this effort."
  date: today
  date-format: long
  sharing: [twitter, facebook, linkedin]
  downloads: [pdf, docx]
  sidebar:
    search: true
    logo: assets/phuse.png
  chapters:
    - index.qmd
    #- intro.qmd
    - summary.qmd
    - why.qmd
    - trust.qmd
    - doc_trust.qmd
    - cost.qmd
    - reg_accept.qmd
    - art.qmd
    - users.qmd
    - user_dev.qmd
    - match.qmd
    - longrun.qmd
    - fundOS.qmd
    - liability.qmd
    - legal.qmd
    - OSmodels.qmd
    - whatelse.qmd
    - contribute.qmd
    - resources.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    number-sections: true
    highlight-style: github

editor: visual

